amcl:
  ros__parameters:
    alpha1: 0.05
    alpha2: 0.05
    alpha3: 0.05
    alpha4: 0.05
    alpha5: 0.05
    always_reset_initial_pose: true
    base_frame_id: base_link
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    first_map_only: false
    global_frame_id: map
    initial_pose:
      x: 0.0
      y: 0.0
      yaw: 0.0
      z: 0.0
    initial_pose_covariance:
      x: 0.25
      y: 0.25
      yaw: 0.068
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: likelihood_field
    max_beams: 60
    max_particles: 1500
    min_particles: 500
    odom_frame_id: odom
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: nav2_amcl::OmniMotionModel
    save_pose_rate: 0.5
    scan_topic: scan
    set_initial_pose: true
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.3
    update_min_a: 0.1
    update_min_d: 0.1
    use_sim_time: true
    z_hit: 0.8
    z_max: 0.05
    z_rand: 0.1
    z_short: 0.05
behavior_server:
  ros__parameters:
    backup:
      plugin: nav2_behaviors/BackUp
    behavior_plugins:
    - spin
    - backup
    - drive_on_heading
    - wait
    costmap_topic: local_costmap/costmap_raw
    cycle_frequency: 10.0
    drive_on_heading:
      plugin: nav2_behaviors/DriveOnHeading
    footprint_topic: local_costmap/published_footprint
    global_frame: odom
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    robot_base_frame: base_footprint
    rotational_acc_lim: 3.2
    simulate_ahead_time: 2.0
    spin:
      plugin: nav2_behaviors/Spin
    transform_tolerance: 0.1
    use_sim_time: true
    wait:
      plugin: nav2_behaviors/Wait
bt_navigator:
  ros__parameters:
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: true
    global_frame: map
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    odom_topic: /odom
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_compute_path_through_poses_action_bt_node
    - nav2_smooth_path_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_drive_on_heading_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_globally_updated_goal_condition_bt_node
    - nav2_is_path_valid_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_truncate_path_local_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_path_expiring_timer_condition
    - nav2_distance_traveled_condition_bt_node
    - nav2_single_trigger_bt_node
    - nav2_is_battery_low_condition_bt_node
    - nav2_navigate_through_poses_action_bt_node
    - nav2_navigate_to_pose_action_bt_node
    - nav2_remove_passed_goals_action_bt_node
    - nav2_planner_selector_bt_node
    - nav2_controller_selector_bt_node
    - nav2_goal_checker_selector_bt_node
    - nav2_controller_cancel_bt_node
    - nav2_path_longer_on_approach_bt_node
    - nav2_wait_cancel_bt_node
    - nav2_spin_cancel_bt_node
    - nav2_back_up_cancel_bt_node
    - nav2_drive_on_heading_cancel_bt_node
    robot_base_frame: base_footprint
    use_sim_time: true
controller_server:
  ros__parameters:
    FollowPath:
      BaseObstacle.scale: 0.01
      GoalAlign.forward_point_distance: 0.3
      GoalAlign.scale: 18.0
      GoalDist.scale: 20.0
      PathAlign.forward_point_distance: 0.3
      PathAlign.scale: 20.0
      PathDist.scale: 28.0
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.scale: 15.0
      RotateToGoal.slowing_factor: 5.0
      acc_lim_theta: 4.0
      acc_lim_x: 3.0
      acc_lim_y: 3.0
      angular_granularity: 0.025
      critics:
      - RotateToGoal
      - Oscillation
      - BaseObstacle
      - GoalAlign
      - PathAlign
      - PathDist
      - GoalDist
      debug_trajectory_details: true
      decel_lim_theta: -4.0
      decel_lim_x: -3.0
      decel_lim_y: -3.0
      linear_granularity: 0.05
      max_speed_xy: 0.5
      max_vel_theta: 2.0
      max_vel_x: 0.5
      max_vel_y: 0.5
      min_speed_theta: 0.0
      min_speed_xy: 0.0
      min_vel_x: 0.0
      min_vel_y: -0.5
      plugin: dwb_core::DWBLocalPlanner
      short_circuit_trajectory_evaluation: true
      sim_time: 1.2
      stateful: true
      trans_stopped_velocity: 0.25
      transform_tolerance: 0.2
      vtheta_samples: 10
      vx_samples: 6
      vy_samples: 5
      xy_goal_tolerance: 0.25
    controller_frequency: 20.0
    controller_plugins:
    - FollowPath
    failure_tolerance: 0.3
    general_goal_checker:
      plugin: nav2_controller::SimpleGoalChecker
      stateful: true
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    goal_checker_plugins:
    - general_goal_checker
    min_theta_velocity_threshold: 0.001
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    progress_checker:
      movement_time_allowance: 10.0
      plugin: nav2_controller::SimpleProgressChecker
      required_movement_radius: 0.5
    progress_checker_plugin: progress_checker
    use_sim_time: true
global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: true
      global_frame: map
      inflation_layer:
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        plugin: nav2_costmap_2d::InflationLayer
      obstacle_layer:
        enabled: true
        observation_sources: scan
        plugin: nav2_costmap_2d::ObstacleLayer
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
      plugins:
      - static_layer
      - obstacle_layer
      - inflation_layer
      publish_frequency: 1.0
      resolution: 0.05
      robot_base_frame: base_footprint
      robot_radius: 0.25
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      track_unknown_space: true
      update_frequency: 1.0
      use_sim_time: true
local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: true
      global_frame: odom
      height: 3
      inflation_layer:
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
        plugin: nav2_costmap_2d::InflationLayer
      plugins:
      - voxel_layer
      - inflation_layer
      publish_frequency: 0.5
      resolution: 0.1
      robot_base_frame: base_footprint
      robot_radius: 0.25
      rolling_window: true
      static_layer:
        map_subscribe_transient_local: true
        plugin: nav2_costmap_2d::StaticLayer
      update_frequency: 1.0
      use_sim_time: true
      voxel_layer:
        enabled: true
        mark_threshold: 0
        max_obstacle_height: 2.0
        observation_sources: scan
        origin_z: 0.0
        plugin: nav2_costmap_2d::VoxelLayer
        publish_voxel_map: false
        scan:
          clearing: true
          data_type: LaserScan
          marking: true
          max_obstacle_height: 2.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          topic: /scan
        z_resolution: 0.05
        z_voxels: 8
      width: 3
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: /home/lonewolf/Desktop/Project/install/robot_gazebo/share/robot_gazebo/maps/map_01.yaml
planner_server:
  ros__parameters:
    GridBased:
      allow_unknown: true
      plugin: nav2_navfn_planner/NavfnPlanner
      tolerance: 2.0
      use_astar: false
    expected_planner_frequency: 1.0
    planner_plugins:
    - GridBased
    use_sim_time: true
velocity_smoother:
  ros__parameters:
    deadband_velocity:
    - 0.0
    - 0.0
    - 0.0
    feedback: OPEN_LOOP
    max_accel:
    - 3.0
    - 3.0
    - 4.0
    max_decel:
    - -3.0
    - -3.0
    - -4.0
    max_velocity:
    - 0.5
    - 0.5
    - 2.0
    min_velocity:
    - 0.0
    - -0.5
    - -2.0
    odom_duration: 0.1
    odom_topic: odom
    scale_velocities: false
    smoothing_frequency: 20.0
    use_sim_time: true
    velocity_timeout: 1.0
waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    use_sim_time: true
    wait_at_waypoint:
      enabled: true
      plugin: nav2_waypoint_follower::WaitAtWaypoint
      waypoint_pause_duration: 200
    waypoint_task_executor_plugin: wait_at_waypoint
